# SPDX-License-Identifier: GPL-2.0
#
# Spacemit Clock specific Makefile
#

obj-$(CONFIG_SPACEMIT_CCU)	+= ccu_pll.o ccu_mix.o ccu_ddn.o
obj-$(CONFIG_SPACEMIT_K1_CCU)	+= ccu-k1.o
obj-$(CONFIG_SPACEMIT_K3_CCU)	+= ccu-k3.o

