# SPDX-License-Identifier: GPL-2.0
#
# Spacemit Clock specific Makefile
#

obj-$(CONFIG_SPACEMIT_K1_CCU)     += ccu-spacemit-k1.o
obj-$(CONFIG_SPACEMIT_K1_CCU)     += ccu_mix.o
obj-$(CONFIG_SPACEMIT_K1_CCU)     += ccu_pll.o
obj-$(CONFIG_SPACEMIT_K1_CCU)     += ccu_dpll.o
obj-$(CONFIG_SPACEMIT_K1_CCU)     += ccu_ddn.o
obj-$(CONFIG_SPACEMIT_K1_CCU)     += ccu_ddr.o
