# SPDX-License-Identifier: GPL-2.0
#
# Spacemit Clock specific Makefile
#

obj-$(CONFIG_SPACEMIT_K3_CCU)	= spacemit-ccu-k3.o
spacemit-ccu-k3-y		= ccu_pll.o ccu_mix.o ccu_ddn.o
spacemit-ccu-k3-y		+= ccu-k1.o

