dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-bananapi-f3.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-muse-pi-pro.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-muse-pi.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-milkv-jupiter.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3-pico.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3-com260.dtb
obj-$(CONFIG_BUILTIN_DTB) += $(addsuffix .o, $(dtb-y))
