// SPDX-License-Identifier: GPL-2.0-only

/* SpacemiT reset controller driver */

#include <linux/auxiliary_bus.h>
#include <linux/container_of.h>
#include <linux/device.h>
#include <linux/module.h>
#include <linux/regmap.h>
#include <linux/reset-controller.h>
#include <linux/types.h>
#include <soc/spacemit/k3-syscon.h>
#include <dt-bindings/clock/spacemit,k3-syscon.h>
#include "reset-spacemit.h"

static const struct ccu_reset_data k3_mpmu_resets[] = {
	[RESET_MPMU_WDT]	= RESET_DATA(MPMU_WDTPCR,	BIT(2), 0),
	[RESET_MPMU_RIPC]	= RESET_DATA(MPMU_RIPCCR,	BIT(2), 0),
};

const struct ccu_reset_controller_data k3_mpmu_reset_data = {
	.reset_data	= k3_mpmu_resets,
	.count		= ARRAY_SIZE(k3_mpmu_resets),
};

static const struct ccu_reset_data k3_apbc_resets[] = {
	[RESET_APBC_UART0]	= RESET_DATA(APBC_UART0_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART2]	= RESET_DATA(APBC_UART2_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART3]	= RESET_DATA(APBC_UART3_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART4]	= RESET_DATA(APBC_UART4_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART5]	= RESET_DATA(APBC_UART5_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART6]	= RESET_DATA(APBC_UART6_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART7]	= RESET_DATA(APBC_UART7_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART8]	= RESET_DATA(APBC_UART8_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART9]	= RESET_DATA(APBC_UART9_CLK_RST,	BIT(2),	0),
	[RESET_APBC_UART10]	= RESET_DATA(APBC_UART10_CLK_RST,	BIT(2),	0),
	[RESET_APBC_GPIO]	= RESET_DATA(APBC_GPIO_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM0]	= RESET_DATA(APBC_PWM0_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM1]	= RESET_DATA(APBC_PWM1_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM2]	= RESET_DATA(APBC_PWM2_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM3]	= RESET_DATA(APBC_PWM3_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM4]	= RESET_DATA(APBC_PWM4_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM5]	= RESET_DATA(APBC_PWM5_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM6]	= RESET_DATA(APBC_PWM6_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM7]	= RESET_DATA(APBC_PWM7_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM8]	= RESET_DATA(APBC_PWM8_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM9]	= RESET_DATA(APBC_PWM9_CLK_RST,		BIT(2), 0),
	[RESET_APBC_PWM10]	= RESET_DATA(APBC_PWM10_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM11]	= RESET_DATA(APBC_PWM11_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM12]	= RESET_DATA(APBC_PWM12_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM13]	= RESET_DATA(APBC_PWM13_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM14]	= RESET_DATA(APBC_PWM14_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM15]	= RESET_DATA(APBC_PWM15_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM16]	= RESET_DATA(APBC_PWM16_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM17]	= RESET_DATA(APBC_PWM17_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM18]	= RESET_DATA(APBC_PWM18_CLK_RST,	BIT(2), 0),
	[RESET_APBC_PWM19]	= RESET_DATA(APBC_PWM19_CLK_RST,	BIT(2), 0),
	[RESET_APBC_SPI0]	= RESET_DATA(APBC_SSP0_CLK_RST,		BIT(2), 0),
	[RESET_APBC_SPI1]	= RESET_DATA(APBC_SSP1_CLK_RST,		BIT(2), 0),
	[RESET_APBC_SPI3]	= RESET_DATA(APBC_SSP3_CLK_RST,		BIT(2), 0),
	[RESET_APBC_RTC]	= RESET_DATA(APBC_RTC_CLK_RST,		BIT(2), 0),
	[RESET_APBC_TWSI0]	= RESET_DATA(APBC_TWSI0_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TWSI1]	= RESET_DATA(APBC_TWSI1_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TWSI2]	= RESET_DATA(APBC_TWSI2_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TWSI4]	= RESET_DATA(APBC_TWSI4_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TWSI5]	= RESET_DATA(APBC_TWSI5_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TWSI6]	= RESET_DATA(APBC_TWSI6_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TWSI8]	= RESET_DATA(APBC_TWSI8_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TIMERS0]	= RESET_DATA(APBC_TIMERS0_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TIMERS1]	= RESET_DATA(APBC_TIMERS1_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TIMERS2]	= RESET_DATA(APBC_TIMERS2_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TIMERS3]	= RESET_DATA(APBC_TIMERS3_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TIMERS4]	= RESET_DATA(APBC_TIMERS4_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TIMERS5]	= RESET_DATA(APBC_TIMERS5_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TIMERS6]	= RESET_DATA(APBC_TIMERS6_CLK_RST,	BIT(2), 0),
	[RESET_APBC_TIMERS7]	= RESET_DATA(APBC_TIMERS7_CLK_RST,	BIT(2), 0),
	[RESET_APBC_AIB]	= RESET_DATA(APBC_AIB_CLK_RST,		BIT(2), 0),
	[RESET_APBC_ONEWIRE]	= RESET_DATA(APBC_ONEWIRE_CLK_RST,	BIT(2), 0),
	[RESET_APBC_I2S0]	= RESET_DATA(APBC_SSPA0_CLK_RST,	BIT(2), 0),
	[RESET_APBC_I2S1]	= RESET_DATA(APBC_SSPA1_CLK_RST,	BIT(2), 0),
	[RESET_APBC_I2S2]	= RESET_DATA(APBC_SSPA2_CLK_RST,	BIT(2), 0),
	[RESET_APBC_I2S3]	= RESET_DATA(APBC_SSPA3_CLK_RST,	BIT(2), 0),
	[RESET_APBC_I2S4]	= RESET_DATA(APBC_SSPA4_CLK_RST,	BIT(2), 0),
	[RESET_APBC_I2S5]	= RESET_DATA(APBC_SSPA5_CLK_RST,	BIT(2), 0),
	[RESET_APBC_DRO]	= RESET_DATA(APBC_DRO_CLK_RST,		BIT(2), 0),
	[RESET_APBC_IR0]	= RESET_DATA(APBC_IR0_CLK_RST,		BIT(2), 0),
	[RESET_APBC_IR1]	= RESET_DATA(APBC_IR1_CLK_RST,		BIT(2), 0),
	[RESET_APBC_TSEN]	= RESET_DATA(APBC_TSEN_CLK_RST,		BIT(2), 0),
	[RESET_IPC_AP2AUD]	= RESET_DATA(APBC_IPC_AP2AUD_CLK_RST,	BIT(2), 0),
	[RESET_APBC_CAN0]	= RESET_DATA(APBC_CAN0_CLK_RST,		BIT(2), 0),
	[RESET_APBC_CAN1]	= RESET_DATA(APBC_CAN1_CLK_RST,		BIT(2), 0),
	[RESET_APBC_CAN2]	= RESET_DATA(APBC_CAN2_CLK_RST,		BIT(2), 0),
	[RESET_APBC_CAN3]	= RESET_DATA(APBC_CAN3_CLK_RST,		BIT(2), 0),
	[RESET_APBC_CAN4]	= RESET_DATA(APBC_CAN4_CLK_RST,		BIT(2), 0),
};

const struct ccu_reset_controller_data k3_apbc_reset_data = {
	.reset_data	= k3_apbc_resets,
	.count		= ARRAY_SIZE(k3_apbc_resets),
};

static const struct ccu_reset_data k3_apmu_resets[] = {
	[RESET_APMU_CSI]	= RESET_DATA(APMU_CSI_CCIC2_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_CCIC2PHY]	= RESET_DATA(APMU_CSI_CCIC2_CLK_RES_CTRL,	0, BIT(2)),
	[RESET_APMU_CCIC3PHY]	= RESET_DATA(APMU_CSI_CCIC2_CLK_RES_CTRL,	0, BIT(29)),
	[RESET_APMU_ISP_CIBUS]	= RESET_DATA(APMU_ISP_CLK_RES_CTRL,		0, BIT(16)),
	[RESET_APMU_DSI_ESC]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL1,	0, BIT(3)),
	[RESET_APMU_LCD]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL1,	0, BIT(4)),
	[RESET_APMU_V2D]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL1,	0, BIT(27)),
	[RESET_APMU_LCD_MCLK]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL2,	0, BIT(9)),
	[RESET_APMU_LCD_DSCCLK]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL2,	0, BIT(15)),
	[RESET_APMU_SC2_HCLK]	= RESET_DATA(APMU_CCIC_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_CCIC_4X]	= RESET_DATA(APMU_CCIC_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_CCIC1_PHY]	= RESET_DATA(APMU_CCIC_CLK_RES_CTRL,	0, BIT(2)),
	[RESET_APMU_SDH_AXI]	= RESET_DATA(APMU_SDH0_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_SDH0]	= RESET_DATA(APMU_SDH0_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_SDH1]	= RESET_DATA(APMU_SDH1_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_SDH2]	= RESET_DATA(APMU_SDH2_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_USB2]	= RESET_DATA(APMU_USB_CLK_RES_CTRL,	0,
				BIT(1)|BIT(2)|BIT(3)),
	[RESET_APMU_USB3_PORTA]	= RESET_DATA(APMU_USB_CLK_RES_CTRL,	0,
				BIT(5)|BIT(6)|BIT(7)),
	[RESET_APMU_USB3_PORTB]	= RESET_DATA(APMU_USB_CLK_RES_CTRL,	0,
				BIT(9)|BIT(10)|BIT(11)),
	[RESET_APMU_USB3_PORTC]	= RESET_DATA(APMU_USB_CLK_RES_CTRL,	0,
				BIT(13)|BIT(14)|BIT(15)),
	[RESET_APMU_USB3_PORTD]	= RESET_DATA(APMU_USB_CLK_RES_CTRL,	0,
				BIT(17)|BIT(18)|BIT(19)),
	[RESET_APMU_QSPI]	= RESET_DATA(APMU_QSPI_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_QSPI_BUS]	= RESET_DATA(APMU_QSPI_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_DMA]	= RESET_DATA(APMU_DMA_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_AES_WTM]	= RESET_DATA(APMU_AES_CLK_RES_CTRL,	0, BIT(4)),
	[RESET_APMU_MCB_DCLK]	= RESET_DATA(APMU_MCB_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_MCB_ACLK]	= RESET_DATA(APMU_MCB_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_VPU]	= RESET_DATA(APMU_VPU_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_DTC]	= RESET_DATA(APMU_DTC_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_GPU]	= RESET_DATA(APMU_GPU_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_MC]		= RESET_DATA(APMU_PMUA_MC_CTRL,		0, BIT(0)),
	[RESET_APMU_CPU0_POP]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(0), 0),
	[RESET_APMU_CPU0_SW]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(1), 0),
	[RESET_APMU_CPU1_POP]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(3), 0),
	[RESET_APMU_CPU1_SW]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(4), 0),
	[RESET_APMU_CPU2_POP]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(6), 0),
	[RESET_APMU_CPU2_SW]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(7), 0),
	[RESET_APMU_CPU3_POP]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(9), 0),
	[RESET_APMU_CPU3_SW]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(10), 0),
	[RESET_APMU_C0_MPSUB_SW]	= RESET_DATA(APMU_PMU_CC2_AP,	BIT(12), 0),
	[RESET_APMU_CPU4_POP]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(16), 0),
	[RESET_APMU_CPU4_SW]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(17), 0),
	[RESET_APMU_CPU5_POP]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(19), 0),
	[RESET_APMU_CPU5_SW]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(20), 0),
	[RESET_APMU_CPU6_POP]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(22), 0),
	[RESET_APMU_CPU6_SW]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(23), 0),
	[RESET_APMU_CPU7_POP]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(25), 0),
	[RESET_APMU_CPU7_SW]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(26), 0),
	[RESET_APMU_C1_MPSUB_SW]	= RESET_DATA(APMU_PMU_CC2_AP,	BIT(28), 0),
	[RESET_APMU_MPSUB_DBG]	= RESET_DATA(APMU_PMU_CC2_AP,		BIT(29), 0),
	[RESET_APMU_UCIE]	= RESET_DATA(APMU_UCIE_CTRL,
				BIT(1) | BIT(2) | BIT(3), 0),
	[RESET_APMU_RCPU]	= RESET_DATA(APMU_RCPU_CLK_RES_CTRL,	0,
				BIT(3) | BIT(2) | BIT(0)),
	[RESET_APMU_DSI4LN2_ESCCLK]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL3,	0, BIT(3)),
	[RESET_APMU_DSI4LN2_LCD_SW]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL3,	0, BIT(4)),
	[RESET_APMU_DSI4LN2_LCD_MCLK]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL4,	0, BIT(9)),
	[RESET_APMU_DSI4LN2_LCD_DSCCLK]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL4,	0, BIT(15)),
	[RESET_APMU_DSI4LN2_DPU_ACLK]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL5,	0, BIT(0)),
	[RESET_APMU_DPU_ACLK]	= RESET_DATA(APMU_LCD_CLK_RES_CTRL5,	0, BIT(15)),
	[RESET_APMU_UFS_ACLK]	= RESET_DATA(APMU_UFS_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_EDP0]	= RESET_DATA(APMU_LCD_EDP_CTRL,		0, BIT(0)),
	[RESET_APMU_EDP1]	= RESET_DATA(APMU_LCD_EDP_CTRL,		0, BIT(16)),
	[RESET_APMU_PCIE_PORTA]	= RESET_DATA(APMU_PCIE_CLK_RES_CTRL_A,	0,
				BIT(5) | BIT(4) | BIT(3)),
	[RESET_APMU_PCIE_PORTB]	= RESET_DATA(APMU_PCIE_CLK_RES_CTRL_B,	0,
				BIT(5) | BIT(4) | BIT(3)),
	[RESET_APMU_PCIE_PORTC]	= RESET_DATA(APMU_PCIE_CLK_RES_CTRL_C,	0,
				BIT(5) | BIT(4) | BIT(3)),
	[RESET_APMU_PCIE_PORTD]	= RESET_DATA(APMU_PCIE_CLK_RES_CTRL_D,	0,
				BIT(5) | BIT(4) | BIT(3)),
	[RESET_APMU_PCIE_PORTE]	= RESET_DATA(APMU_PCIE_CLK_RES_CTRL_E,	0,
				BIT(5) | BIT(4) | BIT(3)),
	[RESET_APMU_EMAC0]	= RESET_DATA(APMU_EMAC0_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_EMAC1]	= RESET_DATA(APMU_EMAC1_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_EMAC2]	= RESET_DATA(APMU_EMAC2_CLK_RES_CTRL,	0, BIT(1)),
	[RESET_APMU_ESPI_MCLK]	= RESET_DATA(APMU_ESPI_CLK_RES_CTRL,	0, BIT(0)),
	[RESET_APMU_ESPI_SCLK]	= RESET_DATA(APMU_ESPI_CLK_RES_CTRL,	0, BIT(2)),
};

const struct ccu_reset_controller_data k3_apmu_reset_data = {
	.reset_data	= k3_apmu_resets,
	.count		= ARRAY_SIZE(k3_apmu_resets),
};

static const struct ccu_reset_data k3_dciu_resets[] = {
	[RESET_DCIU_HDMA]	= RESET_DATA(DCIU_DMASYS_RSTN,		0, BIT(0)),
	[RESET_DCIU_DMA350]	= RESET_DATA(DCIU_DMASYS_SDMA_RSTN,	0, BIT(0)),
	[RESET_DCIU_DMA350_0]	= RESET_DATA(DCIU_DMASYS_S0_RSTN,	0, BIT(0)),
	[RESET_DCIU_DMA350_1]	= RESET_DATA(DCIU_DMASYS_S1_RSTN,	0, BIT(0)),
	[RESET_DCIU_AXIDMA0]	= RESET_DATA(DCIU_DMASYS_A0_RSTN,	0, BIT(0)),
	[RESET_DCIU_AXIDMA1]	= RESET_DATA(DCIU_DMASYS_A1_RSTN,	0, BIT(0)),
	[RESET_DCIU_AXIDMA2]	= RESET_DATA(DCIU_DMASYS_A2_RSTN,	0, BIT(0)),
	[RESET_DCIU_AXIDMA3]	= RESET_DATA(DCIU_DMASYS_A3_RSTN,	0, BIT(0)),
	[RESET_DCIU_AXIDMA4]	= RESET_DATA(DCIU_DMASYS_A4_RSTN,	0, BIT(0)),
	[RESET_DCIU_AXIDMA5]	= RESET_DATA(DCIU_DMASYS_A5_RSTN,	0, BIT(0)),
	[RESET_DCIU_AXIDMA6]	= RESET_DATA(DCIU_DMASYS_A6_RSTN,	0, BIT(0)),
	[RESET_DCIU_AXIDMA7]	= RESET_DATA(DCIU_DMASYS_A7_RSTN,	0, BIT(0)),
};

const struct ccu_reset_controller_data k3_dciu_reset_data = {
	.reset_data	= k3_dciu_resets,
	.count		= ARRAY_SIZE(k3_dciu_resets),
};

static const struct ccu_reset_data k3_rsysctrl_resets[] = {
	[RESET_RCPU_SYSCTRL_RCAN0]	= RESET_DATA(RCPU_CAN_CLK_RST,	0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RCAN1]	= RESET_DATA(RCPU_CAN1_CLK_RST,	0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RCAN2]	= RESET_DATA(RCPU_CAN2_CLK_RST,	0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RCAN3]	= RESET_DATA(RCPU_CAN3_CLK_RST,	0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RCAN4]	= RESET_DATA(RCPU_CAN4_CLK_RST,	0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RIRC0]	= RESET_DATA(RCPU_IRC_CLK_RST,	0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RIRC1]	= RESET_DATA(RCPU_IRC1_CLK_RST,	0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RGMAC]	= RESET_DATA(RCPU_GMAC_CLK_RST,	0, BIT(1)),
	[RESET_RCPU_SYSCTRL_RESPI]	= RESET_DATA(RCPU_ESPI_CLK_RST,	0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RI2S0_SYSCLK]	= RESET_DATA(RCPU_AUDIO_I2S0_SYS_CLK_CTRL,
				0, BIT(0)),
	[RESET_RCPU_SYSCTRL_RI2S1_SYSCLK]	= RESET_DATA(RCPU_AUDIO_I2S1_SYS_CLK_CTRL,
				0, BIT(0)),
};

const struct ccu_reset_controller_data k3_rsysctrl_reset_data = {
	.reset_data	= k3_rsysctrl_resets,
	.count		= ARRAY_SIZE(k3_rsysctrl_resets),
};

static const struct ccu_reset_data k3_ruartctrl_resets[] = {
	[RESET_RCPU_UARTCTRL_RUART0]	= RESET_DATA(RCPU1_UART0_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_UARTCTRL_RUART1]	= RESET_DATA(RCPU1_UART1_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_UARTCTRL_RUART2]	= RESET_DATA(RCPU1_UART2_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_UARTCTRL_RUART3]	= RESET_DATA(RCPU1_UART3_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_UARTCTRL_RUART4]	= RESET_DATA(RCPU1_UART4_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_UARTCTRL_RUART5]	= RESET_DATA(RCPU1_UART5_CLK_RST,	BIT(2), 0),
};

const struct ccu_reset_controller_data k3_ruartctrl_reset_data = {
	.reset_data	= k3_ruartctrl_resets,
	.count		= ARRAY_SIZE(k3_ruartctrl_resets),
};

static const struct ccu_reset_data k3_ri2sctrl_resets[] = {
	[RESET_RCPU_I2SCTRL_RI2S0]	= RESET_DATA(RCPU2_AUDIO_I2S0_TX_RX_CLK_CTRL,	0, BIT(0)),
	[RESET_RCPU_I2SCTRL_RI2S1]	= RESET_DATA(RCPU2_AUDIO_I2S1_TX_RX_CLK_CTRL,	0, BIT(0)),
	[RESET_RCPU_I2SCTRL_RI2S2]	= RESET_DATA(RCPU2_AUDIO_I2S2_TX_RX_CLK_CTRL,	0, BIT(0)),
	[RESET_RCPU_I2SCTRL_RI2S3]	= RESET_DATA(RCPU2_AUDIO_I2S3_TX_RX_CLK_CTRL,	0, BIT(0)),
	[RESET_RCPU_I2SCTRL_RI2S2_SYSCLK]	= RESET_DATA(RCPU2_AUDIO_I2S2_SYS_CLK_CTRL,
				0, BIT(0)),
	[RESET_RCPU_I2SCTRL_RI2S3_SYSCLK]	= RESET_DATA(RCPU2_AUDIO_I2S3_SYS_CLK_CTRL,
				0, BIT(0)),
};

const struct ccu_reset_controller_data k3_ri2sctrl_reset_data = {
	.reset_data	= k3_ri2sctrl_resets,
	.count		= ARRAY_SIZE(k3_ri2sctrl_resets),
};

static const struct ccu_reset_data k3_rspictrl_resets[] = {
	[RESET_RCPU_SPICTRL_RSPI0]	= RESET_DATA(RCPU3_SSP0_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_SPICTRL_RSPI1]	= RESET_DATA(RCPU3_SSP1_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_SPICTRL_RSPI2]	= RESET_DATA(RCPU3_PWR_SSP_CLK_RST,	BIT(2), 0),
};

const struct ccu_reset_controller_data k3_rspictrl_reset_data = {
	.reset_data	= k3_rspictrl_resets,
	.count		= ARRAY_SIZE(k3_rspictrl_resets),
};

static const struct ccu_reset_data k3_ri2cctrl_resets[] = {
	[RESET_RCPU_I2CCTRL_RI2C0]	= RESET_DATA(RCPU4_I2C0_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_I2CCTRL_RI2C1]	= RESET_DATA(RCPU4_I2C1_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_I2CCTRL_RI2C2]	= RESET_DATA(RCPU4_PWR_I2C_CLK_RST,	BIT(2), 0),
};

const struct ccu_reset_controller_data k3_ri2cctrl_reset_data = {
	.reset_data	= k3_ri2cctrl_resets,
	.count		= ARRAY_SIZE(k3_ri2cctrl_resets),
};

static const struct ccu_reset_data k3_rpmu_resets[] = {
	[RESET_RPMU_RTIMER1]	= RESET_DATA(RCPU5_TIMER1_CLK_RST,		0, BIT(0)),
	[RESET_RPMU_RTIMER2]	= RESET_DATA(RCPU5_TIMER2_CLK_RST,		0, BIT(0)),
	[RESET_RPMU_RTIMER3]	= RESET_DATA(RCPU5_TIMER3_CLK_RST,		0, BIT(0)),
	[RESET_RPMU_RTIMER4]	= RESET_DATA(RCPU5_TIMER4_CLK_RST,		0, BIT(0)),
	[RESET_RPMU_IPC2AP]	= RESET_DATA(RCPU5_AON_PER_CLK_RST_CTRL,	0, BIT(0)),
	[RESET_RPMU_IPC2CP]	= RESET_DATA(RCPU5_AON_PER_CLK_RST_CTRL,	0, BIT(2)),
	[RESET_RPMU_IPC2MSA]	= RESET_DATA(RCPU5_AON_PER_CLK_RST_CTRL,	0, BIT(4)),
	[RESET_RPMU_RT24_CORE0]	= RESET_DATA(RCPU5_RT24_CORE0_SW_RESET,		BIT(0), 0),
	[RESET_RPMU_RT24_CORE1]	= RESET_DATA(RCPU5_RT24_CORE1_SW_RESET,		BIT(0), 0),
	[RESET_RPMU_GPIO]	= RESET_DATA(RCPU5_GPIO_AND_EDGE_CLK_RST,	0, BIT(0)),
	[RESET_RPMU_GPIO_EDGE]	= RESET_DATA(RCPU5_GPIO_AND_EDGE_CLK_RST,	0, BIT(2)),
};

const struct ccu_reset_controller_data k3_rpmu_reset_data = {
	.reset_data	= k3_rpmu_resets,
	.count		= ARRAY_SIZE(k3_rpmu_resets),
};

static const struct ccu_reset_data k3_rpwmctrl_resets[] = {
	[RESET_RCPU_PWMCTRL_PWM0]	= RESET_DATA(RCPU6_PWM0_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM1]	= RESET_DATA(RCPU6_PWM1_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM2]	= RESET_DATA(RCPU6_PWM2_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM3]	= RESET_DATA(RCPU6_PWM3_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM4]	= RESET_DATA(RCPU6_PWM4_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM5]	= RESET_DATA(RCPU6_PWM5_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM6]	= RESET_DATA(RCPU6_PWM6_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM7]	= RESET_DATA(RCPU6_PWM7_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM8]	= RESET_DATA(RCPU6_PWM8_CLK_RST,	BIT(2), 0),
	[RESET_RCPU_PWMCTRL_PWM9]	= RESET_DATA(RCPU6_PWM9_CLK_RST,	BIT(2), 0),
};

const struct ccu_reset_controller_data k3_rpwmctrl_reset_data = {
	.reset_data	= k3_rpwmctrl_resets,
	.count		= ARRAY_SIZE(k3_rpwmctrl_resets),
};

static const struct ccu_reset_data k3_apbc2_resets[] = {
	[RESET_APBC2_SEC_UART1]		= RESET_DATA(APBC2_UART1_CLK_RST,	BIT(2), 0),
	[RESET_APBC2_SEC_SPI2]		= RESET_DATA(APBC2_SSP2_CLK_RST,	BIT(2), 0),
	[RESET_APBC2_SEC_TWSI3]		= RESET_DATA(APBC2_TWSI3_CLK_RST,	BIT(2), 0),
	[RESET_APBC2_SEC_RTC]		= RESET_DATA(APBC2_RTC_CLK_RST,		BIT(2), 0),
	[RESET_APBC2_SEC_TIMERS]	= RESET_DATA(APBC2_TIMERS_CLK_RST,	BIT(2), 0),
	[RESET_APBC2_SEC_GPIO]		= RESET_DATA(APBC2_GPIO_CLK_RST,	BIT(2), 0),
};

const struct ccu_reset_controller_data k3_apbc2_reset_data = {
	.reset_data	= k3_apbc2_resets,
	.count		= ARRAY_SIZE(k3_apbc2_resets),
};
