# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_TH1520_REBOOTMODE)	+= th1520_event.o
obj-$(CONFIG_TH1520_SYSTEM_MONITOR) += th1520_system_monitor.o
obj-$(CONFIG_TH1520_REGDUMP) += th1520_regdump.o
obj-$(CONFIG_TH1520_IOPMP) += th1520-iopmp.o

# npu-ax3386-gpl driver
obj-y += nna/
