# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_TH1520_REBOOTMODE)	+= th1520_event.o

# npu-ax3386-gpl driver
obj-y += nna/

obj-$(CONFIG_VIDEO_VC8000D)    += vpu-vc8000d-kernel/linux/subsys_driver/ vpu-vc8000d-kernel/linux/memalloc/
obj-$(CONFIG_VIDEO_VC8000E)    += vpu-vc8000e-kernel/linux/kernel_module/
obj-$(CONFIG_VIDEO_MEMORY) += video_memory/driver/

obj-y += th1520_regdump.o
obj-$(CONFIG_TH1520_SYSTEM_MONITOR) += th1520_system_monitor.o
