name: rvck ci

on:
  pull_request_target:
    types: [opened,reopened,synchronize]
  issues:
    types: [opened,reopened]
  issue_comment:
    types: [created]

jobs:
  rvck-ci:
    permissions:
      issues: write
      pull-requests: write
    uses: OERV-RVCI/RVCK-RAVA/.github/workflows/rvck-actions.yml@main
    secrets:
      LAVA_TOKEN: ${{ secrets.LAVA_TOKEN }}
      RSYNC_PASSPHRASE: ${{ secrets.RSYNC_PASSPHRASE }}

